a = int(input("Enter a number:"))
b = int(input("Enter a number:"))
add = a+b
sub = a-b
mul = a*b
div = a/b
print("addition = ",add)
print("Subtraction =",sub)
print("Multiplication =",mul)
print("Division =",div)
